version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - ./backend/.env # loads DB_NAME, DB_USER, DB_PASS
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    env_file:
      - ./backend/.env # same .env for DB_HOST override
    environment:
      DB_HOST: db # override host to Docker service name
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: node:18-alpine
    container_name: frontend_app
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run build && npm start"
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
